import React from 'react'

const Comp2 = () => {
  return (
    <>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
        <h1>This is Component 2 </h1>
    </>
  )
}

export default Comp2